title: Lille Kat
description: Social events around problem solving and programming at IT University of Copenhagen
logo: images/animated-lillekat.gif 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
